name: Go

on:
  push:
    tags: ["v*"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install gox
      run: go get github.com/mitchellh/gox

    - name: Build
      run: gox -osarch '!darwin/386' -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

    - name: Check
      run: ls dist/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
